/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Student { 
    id?: string;
    name?: string;
    username?: string;
    email?: string;
    password?: string;
    dob?: string;
    phoneNo?: string;
    school?: string;
}

